# -*- coding: utf-8 -*-
"""LinearRegression_on_Real_Estate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cMzPRDTSEpcxyTFH_FSXf7-PuJGw1G09
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv('/content/drive/MyDrive/real_estate_price_size.csv')

data.head()

data.info()

y=data['price']
x=data['size']

plt.scatter(x,y)

y=data[['price']]
x=data[['size']]

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=150)

from sklearn.linear_model import LinearRegression

lr=LinearRegression()

lr.fit(xtrain,ytrain)

print(lr.intercept_)
print(lr.coef_)

ypred=lr.predict(xtest)

from sklearn.metrics import r2_score

r2_score(ytest,ypred)

lr.predict([[100],[50]])

plt.scatter(xtrain,ytrain,color='b')
plt.plot(xtest,ypred,color='r')

from sklearn.metrics import mean_absolute_error,mean_squared_error

print("mean_absolute_error:",mean_absolute_error(ytest,ypred),"mean_squared_error:",mean_squared_error(ytest,ypred),"root_mean_squared_error:",np.sqrt(mean_squared_error(ytest,ypred)))

3312220440200244